sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt58[QTPACKAGE]
  
script:
  - source /opt/qt58/bin/qt58-env.sh
  - cd src
  - /opt/qt58/bin/qmake -project
  - /opt/qt58/bin/qmake src.pro
  - cd /opt/qt58/include
  - find . -name qtcreatorplugin.pri
  - ls
