sudo: required
dist: trusty
language: generic

script:
  - sudo unlink /usr/bin/gcc && sudo ln -s /usr/bin/gcc-5 /usr/bin/gcc
  - gcc --version
matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - gcc-6
            - g++-6
          sources: &sources
            - ubuntu-toolchain-r-test
        env:
          - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
  - sudo apt-get update -qq
  - eval "${MATRIX_EVAL}"

      
install:
  - sudo apt-get -y install qt58[QTPACKAGE]
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - cd  /opt
  - wget http://download.qt.io/official_releases/qtcreator/4.2/4.2.2/qt-creator-opensource-src-4.2.2.tar.gz
  - tar -xf ./qt-creator-opensource-src-4.2.2.tar.gz
      
notifications:
  email:
    on_success: never
    on_failure: always
script:
  - source /opt/qt58/bin/qt58-env.sh
  - cd $TRAVIS_BUILD_DIR/src
  - touch qt_deps.pri
  - echo "QTC_SOURCE = /opt/qt-creator-opensource-src-4.2.2" > qt_deps.pri
  - echo "QTC_BUILD = /opt/qt58" >> qt_deps.pri
  - echo "LIBS+=-L/opt/qt58/lib/x86_64-linux-gnu/qtcreator/ -L/opt/qt58/lib/x86_64-linux-gnu/qtcreator/plugins" >> qt_deps.pri
  - ls
  - cat ./qt_deps.pri
  - /opt/qt58/bin/qmake src.pro
  - ls
  - cat ./.qmake.stash
  - make
