sudo: required
dist: trusty
language: generic
compiler:
  clang:
    - 3.9
    - 4.0
    - trunk
  gcc:
    - 6.0
    - trunk
std:
  - c++14
  - c++17
  - c++-latest
  
before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
  - sudo apt-get update -qq

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - g++-6
          sources: &sources
            - ubuntu-toolchain-r-test
      
install:
  - sudo apt-get -y install qt58[QTPACKAGE]
  - cd  /opt
  - wget http://download.qt.io/official_releases/qtcreator/4.2/4.2.2/qt-creator-opensource-src-4.2.2.tar.gz
  - tar -xf ./qt-creator-opensource-src-4.2.2.tar.gz
  - export CXX="g++-6"
  
      
notifications:
  email:
    on_success: never
    on_failure: always
script:
  - source /opt/qt58/bin/qt58-env.sh
  - cd $TRAVIS_BUILD_DIR/src
  - touch qt_deps.pri
  - echo "QTC_SOURCE = /opt/qt-creator-opensource-src-4.2.2" > qt_deps.pri
  - echo "QTC_BUILD = /opt/qt58" >> qt_deps.pri
  - ls
  - cat ./qt_deps.pri
  - /opt/qt58/bin/qmake src.pro
  - ls
  - cat ./.qmake.stash
  - g++ -v
  - make