sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt58[QTPACKAGE]
  - cd  /opt
  - wget http://download.qt.io/official_releases/qtcreator/4.2/4.2.2/qt-creator-opensource-src-4.2.2.tar.gz
  - tar -xf ./qt-creator-opensource-src-4.2.2.tar.gz
  
before_script:
  - cd project
  
script:
  - source /opt/qt58/bin/qt58-env.sh
  - cd src
  - export IDE_SOURCE_TREE=/opt/qt-creator-opensource-src-4.2.2
  - export IDE_BUILD_TREE=/opt/qt58
  - /opt/qt58/bin/qmake -project
  - /opt/qt58/bin/qmake src.pro
  - make